### ISSUE TITLE
problem with CRISPRdisco installation

### ISSUE THREAD

**Issue by EugeneEA** [CRISPRlab/CRISPRdisco#7]
Hi, I'm new to docker and some help will be really apriciated: 
I'm trying to install CRISPRdisco following two approaches (from docker container and making my own image). Both approaches - fails while running test.sh on 
'Testing CRISPRdisco test run'  step even though 'Testing CLI (usage should print)' print proper help message. 

I'm getting the following error:

'''
___________Testing CRISPRdisco test run___________
Traceback (most recent call last):
  File "/opt/conda/bin/disco", line 9, in <module>
    load_entry_point('crisprdisco', 'console_scripts', 'disco')()
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/app/crisprdisco/cli/script.py", line 67, in disco
    subject_locations = csvFileInput(infile)
  File "/opt/app/crisprdisco/casPROTidentification.py", line 250, in csvFileInput
    df_single_AIMs = pd.read_csv(path_to_file)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File test/test_infile.csv does not exist
'''

I also tried to run ./disco.sh outside of test.sh cript providing it with proper absolute pathes and get the same error (/home/ealbert/python_projects/olympics/CRISPRdisco/test/test_infile.csv does not exist). But file  test_infile.csv is actually there, so I'm not sure what is the problem and why disco does not recognises files in the system. Could you suggest any reasons for such behavioure?

Best, Eugene

**Comment by abriner** [comment]
If you installed it locally, you need to redirect the code to find the reference files - it is still looking in the docker container. Follow this prompt in the README

![Screen Shot 2019-11-11 at 9 25 44 AM](https://user-images.githubusercontent.com/22744430/68594431-82bf3b00-0465-11ea-9a99-b6abe8d92a47.png)

**Comment by EugeneEA** [comment]
Thanks a lot for the fast answer! 
But I was trying to evoid by-hand installation bacause I do not have a root permission on the server.
Docker is installed and running and I'm added to the docker group to use it without sudo.

I was following "To use docker containers:" and "To make your own docker image if the above code did not run properly:" suggestions in the readme...

Maybe being new to docker I missintrepret "Run CLI inside a docker container: ./disco.sh --help" ?
What exactly does it men "Run CLI inside a docker container"? As far as docker invokes inside the ./disco.sh I assumed that I just need to run ./disco.sh (and ./test.sh) as is ($ ./disco.sh) without any othe prior commands?

**Comment by abriner** [comment]
Have you run `make init` in the directory where you copied the repo?  Sometimes with persmissions if you get it to build the docker container again it runs fine.

**Comment by EugeneEA** [comment]
when exactly should I run "make init"? 

I was following these steps:
1 ) Get code: git clone https://github.com/CRISPRlab/CRISPRdisco.git; cd CRISPRdisco
2) Log in to docker hub with docker login and make docker images for the CLI with make setup
3) Run CLI: ./disco.sh --help

**Comment by abriner** [comment]
Since step 3 gave you the error output, run make init then retry step 3.

**Comment by EugeneEA** [comment]
So I've figured out the problem, maybe some will find it usefull:
I do not have root access on the server which apparently was the problem. After I've added  
  --privileged option to the command in ./disco.sh,  ./test.sh completed sucefully.
